apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmers-deployment
  labels:
    app: farmers-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: farmers-pod
      labels:
        app: farmers-pod
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: farmers-container
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        volumeMounts: 
        - name: azurefileshare
          mountPath: /myawesomefileshare 
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
      volumes: 
      - name: azurefileshare 
        azureFile: 
          secretName: filesharesecret 
          shareName: faceimages 
          readOnly: true
  selector:
    matchLabels:
      app: farmers-pod
---
apiVersion: v1
kind: Service
metadata:
  name: farmers-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: farmers-pod